development:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: LinkedInAggregator_development
  pool: 5
  username: vahur
  password:

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: LinkedInAggregator_test
  pool: 5
  username: vahur
  password:

